name: Test published packages

on:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  test_linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version: [ 'ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'centos:8', 'debian:buster', 'fedora:33', 'archlinux:latest' ]
        node-version: [ 10, 12, 14, 15, 16 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container release ${{ matrix.linux-version }} ${{ matrix.node-version }}


  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ windows-2019, macos-10.15 ]
        node-version: [ 10.x, 12.x, 14.x, 15.x, 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - run: npm test
