name: Test published packages

on:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  test_linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version:
        - ubuntu:16.04
        - ubuntu:18.04
        - ubuntu:20.04
        - ubuntu:21.10
        - debian:buster
        - debian:bullseye
        - fedora:33
        - fedora:34
        - amazonlinux:latest
        node-version: [ 12, 14, 16, 17 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container release ${{ matrix.linux-version }} ${{ matrix.node-version }}
      env:
        MOCHA_TEST_NETWORK: 1


  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ windows-2019, macos-10.15 ]
        node-version: [ 12.x, 14.x, 16.x, 17.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - run: npx yatag
    - run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
